services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: production
        container_name: vitalmind-backend
        env_file:
            - .env
        depends_on:
            - database
            - redis
        ports:
            - "${PORT}:${PORT}"
        expose:
            - "${PORT}"
    database:
        image: postgres:17.6-alpine3.22
        container_name: vitalmind-database
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data

        ports:
            - "${DB_PORT}:5432"
        expose:
            - "${DB_PORT}"

    redis:
        image: redis:8.2.1-alpine3.22
        container_name: vitalmind-redis
        restart: always
        env_file:
            - .env
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - "${REDIS_PORT}:6379"
        expose:
            - "${REDIS_PORT}"
        volumes:
            - redis_data:/data
    
volumes:
    postgres_data:
    redis_data: