

services:
    backend:
        build:
            context: ./backend
            dockerfile: DockerFile
            target: production
        volumes:
            - ./backend:/app
        command: ["uv", "run", "main.py"]