"""Added explicit auto increment true

Revision ID: 7ad0ce71bcf1
Revises: bcb73581b61a
Create Date: 2025-08-29 22:03:08.266861

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "7ad0ce71bcf1"
down_revision: Union[str, Sequence[str], None] = "bcb73581b61a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
