name: Backend Tests

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-22.04   # stable LTS runner

    services:
      postgres:
        image: postgres:16.4-slim
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7.4-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        working-directory: backend
        run: uv sync --all-extras --dev

      - name: Run migrations
        working-directory: backend
        env:
          TEST_DB_USER: test_user
          TEST_DB_PASSWORD: test_password
          TEST_DB_NAME: test_db
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 5432
        run: uv run alembic upgrade head

      - name: Run tests
        working-directory: backend
        env:
          TEST_DB_USER: test_user
          TEST_DB_PASSWORD: test_password
          TEST_DB_NAME: test_db
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 5432
          TEST_REDIS_HOST: localhost
          TEST_REDIS_PORT: 6379
          ENVIRONMENT: test
        run: uv run pytest --maxfail=1 --disable-warnings -q
